[Lab 1] HTML + CSS: Creative website template
mikheev-se/effective-web-course pull request #1
Opened 2022-10-29 17:02 UTC by mikheev-se

Михеев Сергей

2022-11-02 16:49 UTC, annamyamikova requested changes

2022-11-02 16:49 UTC, annamyamikova commented on lab_1/src/reset.css
> +video {
Зачем эти стили🤔
Мне кажется это излишне

2022-11-02 16:49 UTC, annamyamikova commented on lab_1/src/reset.css
> +}
Если это глобальные стили, лучшее наименование будет global.css

2022-11-02 16:49 UTC, annamyamikova commented on lab_1/src/style.css
> +  color: #2d3436;
На будущее, переменные нужно выделять в отдельные переменные

2022-11-02 16:49 UTC, annamyamikova commented on lab_1/src/style.css
> +.default-width {
Так как все стили у нас находятся в одной файле, позволяется использовать комментарии
В React мы используем компонентный подход. Комментарии там ни в коем случае не нужны.
Комментарии нужно давать для блока классов
Не нужно давать комментарий для элементов
Если описываем стили для элемента `p`, то мы понимаем, что это параграф. Комментарий излишен.
Все стили для элементов можно вынести в файл global.css или сгруппировать выше с комментариием `/* Global */`

2022-11-02 16:49 UTC, annamyamikova commented on lab_1/src/style.css
> +  /* width: 17.09%; */
Не должно быть мертвого кода вообще

2022-11-02 16:49 UTC, annamyamikova commented on lab_1/src/style.css
> +@media screen and (max-width: 600px) {
Медиа запросы можно сгруппировать также с одним комментарием

2022-11-02 16:58 UTC, annamyamikova requested changes
- Верстка не проходит проверку на валидность 
- Стили плохо сгруппированы

Дополнительно, на что можно обратить внимание:
- Меню при изменении ширины выглядит не очень
- Основная контент с grid сеткой не должен скроллиться. Кнопка уходит за границы. По идее адаптивность для этого блока не выполняется. Доп баллы не начисляться.
- В footer блоки information и keep in touch плывут


Работа не принята.

2022-11-02 17:12 UTC, annamyamikova commented
По коммитам и названию PR все хорошо

2022-11-03 14:20 UTC, konstantinzelinsky commented
С адаптивностью блока с grid сеткой до сих пор не очень. Готов поставить 12 баллов. Ставить?

2022-11-03 14:36 UTC, mikheev-se commented
@konstantinzelinsky да, спасибо

2022-11-03 14:39 UTC, konstantinzelinsky approved these changes

2022-11-03 14:40 UTC, merged