[Lab 5] ReactJS + MobX: stores, API, axios
mikheev-se/effective-web-course pull request #5
Opened 2022-12-02 12:44 UTC by mikheev-se

Михеев Сергей

2022-12-03 19:13 UTC, annamyamikova requested changes
Что-то не так
<img width="474" alt="Screenshot 2022-12-04 at 01 12 39" src="https://user-images.githubusercontent.com/37665408/205457888-5b4fbf91-580b-44a7-bc16-45cfc50a4cc4.png">

2022-12-04 09:37 UTC, mikheev-se commented
@annamyamikova у меня всё работает.... возможно, у Вас проект был запущен не с localhost, а каким-то другим способом, и поетому выбивает 401 anauthorized, потому что домен не входит в мои authorized referrers. я поменял в своём профиле Marvel "localhost" на "*", можете, пожалуйста, проверить ещё раз?
![untitled](https://user-images.githubusercontent.com/91003484/205483794-710c29d4-13fd-4110-91ed-41843262703a.png)

2022-12-07 19:59 UTC, konstantinzelinsky approved these changes
Принял, не очень понравилось использование getElementById

2022-12-07 19:59 UTC, konstantinzelinsky commented on react-ts/src/api/characters.ts
> +    return {} as Character;
Так не очень хорошо делать. Лучше вернуть null в случае ошибки и обработать этот кейс

2022-12-07 19:59 UTC, konstantinzelinsky commented on react-ts/src/components/Content/Content.tsx
> +              (document.getElementById(textFieldId) as HTMLInputElement).value
В реакте в очень крайних случаях нужно использовать getElementById и подобные методы.
Почему бы в данном случае не использовать стейт или реф?

2022-12-07 19:59 UTC, merged